#!/usr/bin/env python3
import json

# Currency data for all countries
currency_data = {
    "AD": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "AE": {"code": "AED", "name": "UAE Dirham", "symbol": "د.إ"},
    "AF": {"code": "AFN", "name": "Afghan Afghani", "symbol": "؋"},
    "AG": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "AI": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "AL": {"code": "ALL", "name": "Albanian Lek", "symbol": "L"},
    "AM": {"code": "AMD", "name": "Armenian Dram", "symbol": "֏"},
    "AO": {"code": "AOA", "name": "Angolan Kwanza", "symbol": "Kz"},
    "AQ": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "AR": {"code": "ARS", "name": "Argentine Peso", "symbol": "$"},
    "AS": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "AT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "AU": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "AW": {"code": "AWG", "name": "Aruban Florin", "symbol": "ƒ"},
    "AX": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "AZ": {"code": "AZN", "name": "Azerbaijani Manat", "symbol": "₼"},
    "BA": {"code": "BAM", "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "КМ"},
    "BB": {"code": "BBD", "name": "Barbadian Dollar", "symbol": "$"},
    "BD": {"code": "BDT", "name": "Bangladeshi Taka", "symbol": "৳"},
    "BE": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "BF": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "BG": {"code": "BGN", "name": "Bulgarian Lev", "symbol": "лв"},
    "BH": {"code": "BHD", "name": "Bahraini Dinar", "symbol": ".د.ب"},
    "BI": {"code": "BIF", "name": "Burundian Franc", "symbol": "FBu"},
    "BJ": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "BL": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "BM": {"code": "BMD", "name": "Bermudan Dollar", "symbol": "$"},
    "BN": {"code": "BND", "name": "Brunei Dollar", "symbol": "$"},
    "BO": {"code": "BOB", "name": "Bolivian Boliviano", "symbol": "$b"},
    "BR": {"code": "BRL", "name": "Brazilian Real", "symbol": "R$"},
    "BS": {"code": "BSD", "name": "Bahamian Dollar", "symbol": "$"},
    "BT": {"code": "BTN", "name": "Bhutanese Ngultrum", "symbol": "Nu."},
    "BW": {"code": "BWP", "name": "Botswanan Pula", "symbol": "P"},
    "BY": {"code": "BYN", "name": "Belarusian Ruble", "symbol": "Br"},
    "BZ": {"code": "BZD", "name": "Belize Dollar", "symbol": "BZ$"},
    "CA": {"code": "CAD", "name": "Canadian Dollar", "symbol": "$"},
    "CC": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "CD": {"code": "CDF", "name": "Congolese Franc", "symbol": "FC"},
    "CF": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "CG": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "CH": {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF"},
    "CI": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "CK": {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$"},
    "CL": {"code": "CLP", "name": "Chilean Peso", "symbol": "$"},
    "CM": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "CN": {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥"},
    "CO": {"code": "COP", "name": "Colombian Peso", "symbol": "$"},
    "CR": {"code": "CRC", "name": "Costa Rican Colón", "symbol": "₡"},
    "CU": {"code": "CUP", "name": "Cuban Peso", "symbol": "₱"},
    "CV": {"code": "CVE", "name": "Cape Verdean Escudo", "symbol": "$"},
    "CX": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "CY": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "CZ": {"code": "CZK", "name": "Czech Republic Koruna", "symbol": "Kč"},
    "DE": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "DJ": {"code": "DJF", "name": "Djiboutian Franc", "symbol": "Fdj"},
    "DK": {"code": "DKK", "name": "Danish Krone", "symbol": "kr"},
    "DM": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "DO": {"code": "DOP", "name": "Dominican Peso", "symbol": "RD$"},
    "DZ": {"code": "DZD", "name": "Algerian Dinar", "symbol": "دج"},
    "EC": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "EE": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "EG": {"code": "EGP", "name": "Egyptian Pound", "symbol": "£"},
    "ER": {"code": "ERN", "name": "Eritrean Nakfa", "symbol": "Nfk"},
    "ES": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "ET": {"code": "ETB", "name": "Ethiopian Birr", "symbol": "Br"},
    "FI": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "FJ": {"code": "FJD", "name": "Fijian Dollar", "symbol": "$"},
    "FK": {"code": "FKP", "name": "Falkland Islands Pound", "symbol": "£"},
    "FM": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "FO": {"code": "DKK", "name": "Danish Krone", "symbol": "kr"},
    "FR": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "GA": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "GB": {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    "GD": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "GE": {"code": "GEL", "name": "Georgian Lari", "symbol": "₾"},
    "GF": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "GG": {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    "GH": {"code": "GHS", "name": "Ghanaian Cedi", "symbol": "¢"},
    "GI": {"code": "GIP", "name": "Gibraltar Pound", "symbol": "£"},
    "GL": {"code": "DKK", "name": "Danish Krone", "symbol": "kr"},
    "GM": {"code": "GMD", "name": "Gambian Dalasi", "symbol": "D"},
    "GN": {"code": "GNF", "name": "Guinean Franc", "symbol": "FG"},
    "GP": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "GQ": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "GR": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "GS": {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    "GT": {"code": "GTQ", "name": "Guatemalan Quetzal", "symbol": "Q"},
    "GU": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "GW": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "GY": {"code": "GYD", "name": "Guyanaese Dollar", "symbol": "$"},
    "HK": {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "$"},
    "HN": {"code": "HNL", "name": "Honduran Lempira", "symbol": "L"},
    "HR": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "HT": {"code": "HTG", "name": "Haitian Gourde", "symbol": "G"},
    "HU": {"code": "HUF", "name": "Hungarian Forint", "symbol": "Ft"},
    "ID": {"code": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp"},
    "IE": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "IL": {"code": "ILS", "name": "Israeli New Sheqel", "symbol": "₪"},
    "IM": {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    "IN": {"code": "INR", "name": "Indian Rupee", "symbol": "₹"},
    "IO": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "IQ": {"code": "IQD", "name": "Iraqi Dinar", "symbol": "ع.د"},
    "IR": {"code": "IRR", "name": "Iranian Rial", "symbol": "﷼"},
    "IS": {"code": "ISK", "name": "Icelandic Króna", "symbol": "kr"},
    "IT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "JE": {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    "JM": {"code": "JMD", "name": "Jamaican Dollar", "symbol": "J$"},
    "JO": {"code": "JOD", "name": "Jordanian Dinar", "symbol": "JD"},
    "JP": {"code": "JPY", "name": "Japanese Yen", "symbol": "¥"},
    "KE": {"code": "KES", "name": "Kenyan Shilling", "symbol": "KSh"},
    "KG": {"code": "KGS", "name": "Kyrgystani Som", "symbol": "лв"},
    "KH": {"code": "KHR", "name": "Cambodian Riel", "symbol": "៛"},
    "KI": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "KM": {"code": "KMF", "name": "Comorian Franc", "symbol": "CF"},
    "KN": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "KP": {"code": "KPW", "name": "North Korean Won", "symbol": "₩"},
    "KR": {"code": "KRW", "name": "South Korean Won", "symbol": "₩"},
    "KW": {"code": "KWD", "name": "Kuwaiti Dinar", "symbol": "KD"},
    "KY": {"code": "KYD", "name": "Cayman Islands Dollar", "symbol": "$"},
    "KZ": {"code": "KZT", "name": "Kazakhstani Tenge", "symbol": "лв"},
    "LA": {"code": "LAK", "name": "Laotian Kip", "symbol": "₭"},
    "LB": {"code": "LBP", "name": "Lebanese Pound", "symbol": "£"},
    "LC": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "LI": {"code": "CHF", "name": "Swiss Franc", "symbol": "CHF"},
    "LK": {"code": "LKR", "name": "Sri Lankan Rupee", "symbol": "₨"},
    "LR": {"code": "LRD", "name": "Liberian Dollar", "symbol": "$"},
    "LS": {"code": "LSL", "name": "Lesotho Loti", "symbol": "M"},
    "LT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "LU": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "LV": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "LY": {"code": "LYD", "name": "Libyan Dinar", "symbol": "LD"},
    "MA": {"code": "MAD", "name": "Moroccan Dirham", "symbol": "MAD"},
    "MC": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "MD": {"code": "MDL", "name": "Moldovan Leu", "symbol": "lei"},
    "ME": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "MF": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "MG": {"code": "MGA", "name": "Malagasy Ariary", "symbol": "Ar"},
    "MH": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "MK": {"code": "MKD", "name": "Macedonian Denar", "symbol": "ден"},
    "ML": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "MM": {"code": "MMK", "name": "Myanma Kyat", "symbol": "K"},
    "MN": {"code": "MNT", "name": "Mongolian Tugrik", "symbol": "₮"},
    "MO": {"code": "MOP", "name": "Macanese Pataca", "symbol": "MOP$"},
    "MP": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "MQ": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "MR": {"code": "MRU", "name": "Mauritanian Ouguiya", "symbol": "UM"},
    "MS": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "MT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "MU": {"code": "MUR", "name": "Mauritian Rupee", "symbol": "₨"},
    "MV": {"code": "MVR", "name": "Maldivian Rufiyaa", "symbol": "Rf"},
    "MW": {"code": "MWK", "name": "Malawian Kwacha", "symbol": "MK"},
    "MX": {"code": "MXN", "name": "Mexican Peso", "symbol": "$"},
    "MY": {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM"},
    "MZ": {"code": "MZN", "name": "Mozambican Metical", "symbol": "MT"},
    "NA": {"code": "NAD", "name": "Namibian Dollar", "symbol": "$"},
    "NC": {"code": "XPF", "name": "CFP Franc", "symbol": "₣"},
    "NE": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "NF": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "NG": {"code": "NGN", "name": "Nigerian Naira", "symbol": "₦"},
    "NI": {"code": "NIO", "name": "Nicaraguan Córdoba", "symbol": "C$"},
    "NL": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "NO": {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr"},
    "NP": {"code": "NPR", "name": "Nepalese Rupee", "symbol": "₨"},
    "NR": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "NU": {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$"},
    "NZ": {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$"},
    "OM": {"code": "OMR", "name": "Omani Rial", "symbol": "﷼"},
    "PA": {"code": "PAB", "name": "Panamanian Balboa", "symbol": "B/."},
    "PE": {"code": "PEN", "name": "Peruvian Nuevo Sol", "symbol": "S/."},
    "PF": {"code": "XPF", "name": "CFP Franc", "symbol": "₣"},
    "PG": {"code": "PGK", "name": "Papua New Guinean Kina", "symbol": "K"},
    "PH": {"code": "PHP", "name": "Philippine Peso", "symbol": "₱"},
    "PK": {"code": "PKR", "name": "Pakistani Rupee", "symbol": "₨"},
    "PL": {"code": "PLN", "name": "Polish Zloty", "symbol": "zł"},
    "PM": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "PN": {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$"},
    "PR": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "PS": {"code": "ILS", "name": "Israeli New Sheqel", "symbol": "₪"},
    "PT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "PW": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "PY": {"code": "PYG", "name": "Paraguayan Guarani", "symbol": "Gs"},
    "QA": {"code": "QAR", "name": "Qatari Rial", "symbol": "﷼"},
    "RE": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "RO": {"code": "RON", "name": "Romanian Leu", "symbol": "lei"},
    "RS": {"code": "RSD", "name": "Serbian Dinar", "symbol": "Дин."},
    "RU": {"code": "RUB", "name": "Russian Ruble", "symbol": "₽"},
    "RW": {"code": "RWF", "name": "Rwandan Franc", "symbol": "R₣"},
    "SA": {"code": "SAR", "name": "Saudi Riyal", "symbol": "﷼"},
    "SB": {"code": "SBD", "name": "Solomon Islands Dollar", "symbol": "$"},
    "SC": {"code": "SCR", "name": "Seychellois Rupee", "symbol": "₨"},
    "SD": {"code": "SDG", "name": "Sudanese Pound", "symbol": "ج.س."},
    "SE": {"code": "SEK", "name": "Swedish Krona", "symbol": "kr"},
    "SG": {"code": "SGD", "name": "Singapore Dollar", "symbol": "$"},
    "SH": {"code": "SHP", "name": "Saint Helena Pound", "symbol": "£"},
    "SI": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "SJ": {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr"},
    "SK": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "SL": {"code": "SLE", "name": "Sierra Leonean Leone", "symbol": "Le"},
    "SM": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "SN": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "SO": {"code": "SOS", "name": "Somali Shilling", "symbol": "S"},
    "SR": {"code": "SRD", "name": "Surinamese Dollar", "symbol": "$"},
    "SS": {"code": "SSP", "name": "South Sudanese Pound", "symbol": "£"},
    "ST": {"code": "STN", "name": "São Tomé and Príncipe Dobra", "symbol": "Db"},
    "SV": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "SY": {"code": "SYP", "name": "Syrian Pound", "symbol": "£"},
    "SZ": {"code": "SZL", "name": "Swazi Lilangeni", "symbol": "E"},
    "TC": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "TD": {"code": "XAF", "name": "Central African CFA Franc", "symbol": "FCFA"},
    "TG": {"code": "XOF", "name": "West African CFA Franc", "symbol": "CFA"},
    "TH": {"code": "THB", "name": "Thai Baht", "symbol": "฿"},
    "TJ": {"code": "TJS", "name": "Tajikistani Somoni", "symbol": "SM"},
    "TK": {"code": "NZD", "name": "New Zealand Dollar", "symbol": "$"},
    "TL": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "TM": {"code": "TMT", "name": "Turkmenistani Manat", "symbol": "T"},
    "TN": {"code": "TND", "name": "Tunisian Dinar", "symbol": "د.ت"},
    "TO": {"code": "TOP", "name": "Tongan Paʻanga", "symbol": "T$"},
    "TR": {"code": "TRY", "name": "Turkish Lira", "symbol": "₺"},
    "TT": {"code": "TTD", "name": "Trinidad and Tobago Dollar", "symbol": "TT$"},
    "TV": {"code": "AUD", "name": "Australian Dollar", "symbol": "$"},
    "TW": {"code": "TWD", "name": "New Taiwan Dollar", "symbol": "NT$"},
    "TZ": {"code": "TZS", "name": "Tanzanian Shilling", "symbol": "TSh"},
    "UA": {"code": "UAH", "name": "Ukrainian Hryvnia", "symbol": "₴"},
    "UG": {"code": "UGX", "name": "Ugandan Shilling", "symbol": "USh"},
    "US": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "UY": {"code": "UYU", "name": "Uruguayan Peso", "symbol": "$U"},
    "UZ": {"code": "UZS", "name": "Uzbekistan Som", "symbol": "лв"},
    "VA": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "VC": {"code": "XCD", "name": "East Caribbean Dollar", "symbol": "$"},
    "VE": {"code": "VES", "name": "Venezuelan Bolívar", "symbol": "Bs"},
    "VG": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "VI": {"code": "USD", "name": "US Dollar", "symbol": "$"},
    "VN": {"code": "VND", "name": "Vietnamese Dong", "symbol": "₫"},
    "VU": {"code": "VUV", "name": "Vanuatu Vatu", "symbol": "VT"},
    "WF": {"code": "XPF", "name": "CFP Franc", "symbol": "₣"},
    "WS": {"code": "WST", "name": "Samoan Tala", "symbol": "WS$"},
    "YE": {"code": "YER", "name": "Yemeni Rial", "symbol": "﷼"},
    "YT": {"code": "EUR", "name": "Euro", "symbol": "€"},
    "ZA": {"code": "ZAR", "name": "South African Rand", "symbol": "R"},
    "ZM": {"code": "ZMW", "name": "Zambian Kwacha", "symbol": "ZK"},
    "ZW": {"code": "ZWL", "name": "Zimbabwean Dollar", "symbol": "Z$"},
}

def update_countries_json():
    # Read the current JSON file
    with open('public/vendor/countries.json', 'r', encoding='utf-8') as f:
        countries = json.load(f)
    
    # Update each country with currency and flag information
    for country in countries:
        country_code = country['code']
        
        # Add currency information
        if country_code in currency_data:
            country['currency'] = currency_data[country_code]
        
        # Add flag URL (using flagcdn.com with lowercase country code)
        country['flag'] = f"https://flagcdn.com/w320/{country_code.lower()}.png"
        
        # Remove the "image" field since those flag files don't exist
        if 'image' in country:
            del country['image']
    
    # Write the updated JSON back to file
    with open('public/vendor/countries.json', 'w', encoding='utf-8') as f:
        json.dump(countries, f, indent=2, ensure_ascii=False)
    
    print(f"Successfully updated {len(countries)} countries with currency and flag information!")

if __name__ == "__main__":
    update_countries_json()