@extends('central.layouts.app')

@section('title', 'Central Knowledge Base')

@section('content')
<!--begin::App Content Header-->
<div class="app-content-header">
  <!--begin::Container-->
  <div class="container-fluid">
    <!--begin::Row-->
    <div class="row">
      <div class="col-sm-6">
        <h3 class="mb-0">🏢 Central Management Knowledge Base</h3>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-end">
          <li class="breadcrumb-item">
            <a href="{{ route('central.dashboard') }}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Knowledge Base</li>
        </ol>
      </div>
    </div>
    <!--end::Row-->
  </div>
  <!--end::Container-->
</div>
<!--end::App Content Header-->

<!--begin::App Content-->
<div class="app-content">
  <!--begin::Container-->
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <div class="card-title">
              <h4 class="mb-0">📚 Platform Administration Guide</h4>
            </div>
            <div class="card-tools">
              <button type="button" class="btn btn-sm btn-outline-primary" onclick="window.print()">
                <i class="bi bi-printer"></i> Print Guide
              </button>
              <button type="button" class="btn btn-sm btn-outline-info" id="toggleSidebar">
                <i class="bi bi-list"></i> Table of Contents
              </button>
              <button type="button" class="btn btn-sm btn-outline-success" id="searchToggle">
                <i class="bi bi-search"></i> Search
              </button>
            </div>
          </div>
          <div class="card-body">
            <!-- Search Box -->
            <div class="row mb-3" id="searchBox" style="display: none;">
              <div class="col-12">
                <div class="input-group">
                  <input type="text" class="form-control" id="knowledgeSearch" 
                         placeholder="Search through the knowledge base...">
                  <button class="btn btn-outline-secondary" type="button" onclick="clearSearch()">
                    <i class="bi bi-x"></i>
                  </button>
                </div>
              </div>
            </div>

            <div class="row">
              <!-- Table of Contents Sidebar -->
              <div class="col-md-3 d-none d-md-block" id="tocSidebar">
                <div class="sticky-top" style="top: 20px;">
                  <div class="card bg-light">
                    <div class="card-header py-2">
                      <h6 class="mb-0">📋 Quick Navigation</h6>
                    </div>
                    <div class="card-body py-2">
                      <div id="tableOfContents">
                        <!-- TOC will be generated by JavaScript -->
                      </div>
                    </div>
                  </div>

                  <!-- Quick Actions -->
                  <div class="card bg-primary text-white mt-3">
                    <div class="card-header py-2">
                      <h6 class="mb-0">⚡ Quick Actions</h6>
                    </div>
                    <div class="card-body py-2">
                      <div class="d-grid gap-2">
                        <a href="{{ route('central.tenants.create') }}" class="btn btn-light btn-sm">
                          <i class="bi bi-plus"></i> New Tenant
                        </a>
                        <a href="{{ route('central.tenants.index') }}" class="btn btn-light btn-sm">
                          <i class="bi bi-building"></i> Manage Tenants
                        </a>
                        <a href="{{ route('central.plans.index') }}" class="btn btn-light btn-sm">
                          <i class="bi bi-credit-card"></i> Subscription Plans
                        </a>
                        <a href="{{ route('central.dashboard') }}" class="btn btn-light btn-sm">
                          <i class="bi bi-graph-up"></i> Analytics
                        </a>
                      </div>
                    </div>
                  </div>

                  <!-- System Status -->
                  <div class="card bg-success text-white mt-3">
                    <div class="card-header py-2">
                      <h6 class="mb-0">🟢 System Status</h6>
                    </div>
                    <div class="card-body py-2">
                      <div class="small">
                        <div class="d-flex justify-content-between">
                          <span>Platform:</span>
                          <span class="badge bg-light text-dark">Online</span>
                        </div>
                        <div class="d-flex justify-content-between">
                          <span>Database:</span>
                          <span class="badge bg-light text-dark">Healthy</span>
                        </div>
                        <div class="d-flex justify-content-between">
                          <span>Backups:</span>
                          <span class="badge bg-light text-dark">Current</span>
                        </div>
                        <div class="d-flex justify-content-between">
                          <span>Last Update:</span>
                          <span class="badge bg-light text-dark">{{ now()->format('M j') }}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <!-- Main Content -->
              <div class="col-md-9" id="mainContent">
                <div class="knowledge-base-content" style="max-height: 75vh; overflow-y: auto; padding-right: 15px;">
                  {!! \Illuminate\Support\Str::markdown($content) !!}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--end::Container-->
</div>
<!--end::App Content-->

<style>
.knowledge-base-content {
  line-height: 1.7;
  font-size: 15px;
}

.knowledge-base-content h1 {
  color: #2c3e50;
  border-bottom: 3px solid #3498db;
  padding-bottom: 10px;
  margin-top: 30px;
  margin-bottom: 20px;
}

.knowledge-base-content h2 {
  color: #2c3e50;
  border-bottom: 2px solid #e9ecef;
  padding-bottom: 8px;
  margin-top: 25px;
  margin-bottom: 15px;
}

.knowledge-base-content h3 {
  color: #34495e;
  margin-top: 20px;
  margin-bottom: 12px;
  font-weight: 600;
}

.knowledge-base-content h4 {
  color: #5a6c7d;
  margin-top: 15px;
  margin-bottom: 10px;
}

.knowledge-base-content code {
  background-color: #f8f9fa;
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 0.9em;
  color: #e74c3c;
  font-family: 'Monaco', 'Courier New', monospace;
}

.knowledge-base-content pre {
  background-color: #2c3e50;
  color: #ecf0f1;
  border: 1px solid #34495e;
  border-radius: 5px;
  padding: 15px;
  margin: 15px 0;
  overflow-x: auto;
  font-family: 'Monaco', 'Courier New', monospace;
}

.knowledge-base-content pre code {
  background: none;
  padding: 0;
  color: #ecf0f1;
}

.knowledge-base-content blockquote {
  border-left: 4px solid #3498db;
  padding-left: 15px;
  margin: 20px 0;
  background-color: #ecf0f1;
  padding: 15px;
  border-radius: 0 5px 5px 0;
  font-style: italic;
}

.knowledge-base-content ul, .knowledge-base-content ol {
  margin-bottom: 15px;
  padding-left: 25px;
}

.knowledge-base-content li {
  margin-bottom: 5px;
}

.knowledge-base-content table {
  width: 100%;
  margin: 20px 0;
  border-collapse: collapse;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.knowledge-base-content table th,
.knowledge-base-content table td {
  border: 1px solid #bdc3c7;
  padding: 12px;
  text-align: left;
}

.knowledge-base-content table th {
  background-color: #34495e;
  color: white;
  font-weight: 600;
}

.knowledge-base-content table tr:nth-child(even) {
  background-color: #f8f9fa;
}

.knowledge-base-content table tr:hover {
  background-color: #e8f4f8;
}

/* Status badges in content */
.knowledge-base-content .badge {
  font-size: 0.8em;
  padding: 4px 8px;
  border-radius: 12px;
}

/* Alert styles */
.knowledge-base-content .alert {
  padding: 15px;
  margin: 20px 0;
  border: 1px solid transparent;
  border-radius: 5px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.knowledge-base-content .alert-info {
  color: #2980b9;
  background-color: #ebf3fd;
  border-color: #3498db;
}

.knowledge-base-content .alert-warning {
  color: #d68910;
  background-color: #fef9e7;
  border-color: #f39c12;
}

.knowledge-base-content .alert-success {
  color: #27ae60;
  background-color: #eafaf1;
  border-color: #2ecc71;
}

.knowledge-base-content .alert-danger {
  color: #c0392b;
  background-color: #fdedec;
  border-color: #e74c3c;
}

.knowledge-base-content img {
  max-width: 100%;
  height: auto;
  margin: 15px 0;
  border-radius: 5px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

/* TOC Styling */
#tableOfContents {
  max-height: 60vh;
  overflow-y: auto;
}

#tableOfContents a {
  color: #34495e;
  text-decoration: none;
  display: block;
  padding: 5px 0;
  border-bottom: 1px solid #ecf0f1;
  transition: all 0.2s;
}

#tableOfContents a:hover {
  color: #3498db;
  padding-left: 10px;
  background-color: #f8f9fa;
}

#tableOfContents .toc-h1 {
  font-weight: bold;
  margin-top: 10px;
  color: #2c3e50;
}

#tableOfContents .toc-h2 {
  padding-left: 15px;
  font-size: 0.9em;
}

#tableOfContents .toc-h3 {
  padding-left: 30px;
  font-size: 0.85em;
  color: #5a6c7d;
}

/* Search highlighting */
mark {
  background-color: #f1c40f;
  color: #2c3e50;
  padding: 2px 4px;
  border-radius: 3px;
}

/* Print styles */
@media print {
  .card-header,
  .breadcrumb,
  #tocSidebar,
  .btn,
  #searchBox {
    display: none !important;
  }
  
  .card {
    border: none !important;
    box-shadow: none !important;
  }
  
  .col-md-9 {
    flex: 0 0 100% !important;
    max-width: 100% !important;
  }
  
  .knowledge-base-content {
    font-size: 12px !important;
  }
  
  .knowledge-base-content h1 {
    page-break-before: always;
    color: #000 !important;
  }
  
  .knowledge-base-content h1:first-child {
    page-break-before: auto;
  }
  
  .knowledge-base-content pre {
    background-color: #f8f9fa !important;
    color: #000 !important;
    border: 1px solid #000 !important;
  }
}

/* Mobile responsiveness */
@media (max-width: 768px) {
  #tocSidebar {
    display: none !important;
  }
  
  #tocSidebar.show {
    display: block !important;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 1050;
  }
  
  #tocSidebar.show .card {
    position: absolute;
    top: 50px;
    left: 20px;
    right: 20px;
    max-height: calc(100vh - 100px);
    overflow-y: auto;
  }
  
  .col-md-9 {
    flex: 0 0 100% !important;
    max-width: 100% !important;
  }
}

/* Enhanced admin styling */
.knowledge-base-content strong {
  color: #2c3e50;
  font-weight: 600;
}

.knowledge-base-content em {
  color: #5a6c7d;
  font-style: italic;
}

/* Custom admin color scheme */
:root {
  --admin-primary: #3498db;
  --admin-secondary: #2c3e50;
  --admin-success: #27ae60;
  --admin-warning: #f39c12;
  --admin-danger: #e74c3c;
  --admin-info: #17a2b8;
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Generate Table of Contents
    generateTableOfContents();
    
    // Toggle sidebar on mobile
    document.getElementById('toggleSidebar').addEventListener('click', function() {
        const sidebar = document.getElementById('tocSidebar');
        sidebar.classList.toggle('show');
    });
    
    // Toggle search box
    document.getElementById('searchToggle').addEventListener('click', function() {
        const searchBox = document.getElementById('searchBox');
        if (searchBox.style.display === 'none') {
            searchBox.style.display = 'block';
            document.getElementById('knowledgeSearch').focus();
        } else {
            searchBox.style.display = 'none';
            clearSearch();
        }
    });
    
    // Search functionality
    document.getElementById('knowledgeSearch').addEventListener('input', function() {
        searchKnowledgeBase(this.value);
    });
    
    // Close sidebar when clicking outside on mobile
    document.getElementById('tocSidebar').addEventListener('click', function(e) {
        if (e.target === this) {
            this.classList.remove('show');
        }
    });
    
    // Add keyboard shortcuts
    document.addEventListener('keydown', function(e) {
        // Ctrl/Cmd + K for search
        if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
            e.preventDefault();
            document.getElementById('searchToggle').click();
        }
        
        // Escape to close search
        if (e.key === 'Escape') {
            const searchBox = document.getElementById('searchBox');
            if (searchBox.style.display !== 'none') {
                searchBox.style.display = 'none';
                clearSearch();
            }
        }
    });
});

function generateTableOfContents() {
    const headers = document.querySelectorAll('.knowledge-base-content h1, .knowledge-base-content h2, .knowledge-base-content h3');
    const toc = document.getElementById('tableOfContents');
    
    if (headers.length === 0) return;
    
    let tocHTML = '';
    
    headers.forEach((header, index) => {
        // Create unique ID for header
        const id = 'heading-' + index;
        header.id = id;
        
        // Remove emoji from text for cleaner TOC
        const text = header.textContent.replace(/[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu, '').trim();
        
        // Determine heading level
        const level = header.tagName.toLowerCase();
        
        tocHTML += `<a href="#${id}" class="toc-${level}">${text}</a>`;
    });
    
    toc.innerHTML = tocHTML;
    
    // Smooth scrolling for TOC links
    toc.querySelectorAll('a').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
                
                // Close mobile sidebar
                document.getElementById('tocSidebar').classList.remove('show');
            }
        });
    });
}

// Enhanced search functionality
function searchKnowledgeBase(query) {
    const content = document.querySelector('.knowledge-base-content');
    const sections = content.querySelectorAll('h1, h2, h3, h4, p, li, td');
    
    // Clear previous highlights
    sections.forEach(section => {
        section.innerHTML = section.innerHTML.replace(/<mark[^>]*>(.*?)<\/mark>/gi, '$1');
        section.style.display = '';
    });
    
    if (!query || query.length < 2) {
        return;
    }
    
    const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
    let hasResults = false;
    
    sections.forEach(section => {
        const text = section.textContent;
        if (text.match(regex)) {
            hasResults = true;
            section.style.display = '';
            // Highlight matching text
            section.innerHTML = section.innerHTML.replace(regex, '<mark>$1</mark>');
        } else {
            // Only hide content sections, keep headers visible for context
            if (!['H1', 'H2', 'H3', 'H4'].includes(section.tagName)) {
                section.style.display = 'none';
            }
        }
    });
    
    // Show "no results" message if needed
    if (!hasResults && query.length >= 2) {
        showNoResultsMessage(query);
    }
}

function showNoResultsMessage(query) {
    const existingMessage = document.getElementById('noResultsMessage');
    if (existingMessage) {
        existingMessage.remove();
    }
    
    const message = document.createElement('div');
    message.id = 'noResultsMessage';
    message.className = 'alert alert-info mt-3';
    message.innerHTML = `
        <h5><i class="bi bi-info-circle"></i> No Results Found</h5>
        <p>No content found for "<strong>${query}</strong>".</p>
        <p class="mb-0">Try searching for:</p>
        <ul class="mb-0 mt-2">
            <li>Different keywords or phrases</li>
            <li>Broader terms (e.g., "tenant" instead of "tenant creation")</li>
            <li>Check spelling and try alternative terms</li>
        </ul>
    `;
    
    document.querySelector('.knowledge-base-content').insertBefore(
        message, 
        document.querySelector('.knowledge-base-content').firstChild
    );
}

function clearSearch() {
    document.getElementById('knowledgeSearch').value = '';
    searchKnowledgeBase('');
    
    // Remove no results message
    const existingMessage = document.getElementById('noResultsMessage');
    if (existingMessage) {
        existingMessage.remove();
    }
}

// Back to top functionality
window.addEventListener('scroll', function() {
    let backToTop = document.getElementById('backToTop');
    if (!backToTop) {
        // Create back to top button
        const button = document.createElement('button');
        button.id = 'backToTop';
        button.className = 'btn btn-primary position-fixed';
        button.style.cssText = 'bottom: 20px; right: 20px; z-index: 1000; display: none; border-radius: 50%; width: 50px; height: 50px;';
        button.innerHTML = '<i class="bi bi-arrow-up"></i>';
        button.title = 'Back to top';
        button.onclick = () => {
            window.scrollTo({ 
                top: 0, 
                behavior: 'smooth' 
            });
        };
        document.body.appendChild(button);
        backToTop = button;
    }
    
    if (window.pageYOffset > 300) {
        backToTop.style.display = 'block';
    } else {
        backToTop.style.display = 'none';
    }
});

// Add section link functionality
document.querySelectorAll('.knowledge-base-content h1, .knowledge-base-content h2, .knowledge-base-content h3').forEach(header => {
    header.addEventListener('mouseenter', function() {
        if (!this.querySelector('.section-link')) {
            const link = document.createElement('a');
            link.className = 'section-link text-muted ms-2';
            link.href = '#' + this.id;
            link.innerHTML = '<i class="bi bi-link-45deg"></i>';
            link.style.opacity = '0.5';
            link.title = 'Link to this section';
            this.appendChild(link);
        }
    });
});
</script>
@endsection