@extends('tenant.layouts.app')

@section('title', 'Knowledge Base')

@section('content')
<!--begin::App Content Header-->
<div class="app-content-header">
  <!--begin::Container-->
  <div class="container-fluid">
    <!--begin::Row-->
    <div class="row">
      <div class="col-sm-6">
        <h3 class="mb-0">📚 Knowledge Base</h3>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-end">
          <li class="breadcrumb-item">
            <a href="{{ route('tenant.dashboard') }}">Dashboard</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Knowledge Base</li>
        </ol>
      </div>
    </div>
    <!--end::Row-->
  </div>
  <!--end::Container-->
</div>
<!--end::App Content Header-->

<!--begin::App Content-->
<div class="app-content">
  <!--begin::Container-->
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <div class="card-title">
              <h4 class="mb-0">📖 User Guide & Documentation</h4>
            </div>
            <div class="card-tools">
              <button type="button" class="btn btn-sm btn-outline-primary" onclick="window.print()">
                <i class="bi bi-printer"></i> Print Guide
              </button>
              <button type="button" class="btn btn-sm btn-outline-info" id="toggleSidebar">
                <i class="bi bi-list"></i> Table of Contents
              </button>
            </div>
          </div>
          <div class="card-body">
            <div class="row">
              <!-- Table of Contents Sidebar -->
              <div class="col-md-3 d-none d-md-block" id="tocSidebar">
                <div class="sticky-top" style="top: 20px;">
                  <div class="card bg-light">
                    <div class="card-header py-2">
                      <h6 class="mb-0">📋 Quick Navigation</h6>
                    </div>
                    <div class="card-body py-2">
                      <div id="tableOfContents">
                        <!-- TOC will be generated by JavaScript -->
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <!-- Main Content -->
              <div class="col-md-9" id="mainContent">
                <div class="knowledge-base-content" style="max-height: 75vh; overflow-y: auto; padding-right: 15px;">
                  {!! \Illuminate\Support\Str::markdown($content) !!}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--end::Container-->
</div>
<!--end::App Content-->

<style>
.knowledge-base-content {
  line-height: 1.7;
  font-size: 15px;
}

.knowledge-base-content h1 {
  color: #373643;
  border-bottom: 3px solid #18cb96;
  padding-bottom: 10px;
  margin-top: 30px;
  margin-bottom: 20px;
}

.knowledge-base-content h2 {
  color: #373643;
  border-bottom: 2px solid #e9ecef;
  padding-bottom: 8px;
  margin-top: 25px;
  margin-bottom: 15px;
}

.knowledge-base-content h3 {
  color: #495057;
  margin-top: 20px;
  margin-bottom: 12px;
}

.knowledge-base-content h4 {
  color: #6c757d;
  margin-top: 15px;
  margin-bottom: 10px;
}

.knowledge-base-content code {
  background-color: #f8f9fa;
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 0.9em;
  color: #e83e8c;
}

.knowledge-base-content pre {
  background-color: #f8f9fa;
  border: 1px solid #e9ecef;
  border-radius: 5px;
  padding: 15px;
  margin: 15px 0;
  overflow-x: auto;
}

.knowledge-base-content pre code {
  background: none;
  padding: 0;
  color: #373643;
}

.knowledge-base-content blockquote {
  border-left: 4px solid #18cb96;
  padding-left: 15px;
  margin: 20px 0;
  background-color: #f8f9fa;
  padding: 15px;
  border-radius: 0 5px 5px 0;
}

.knowledge-base-content ul, .knowledge-base-content ol {
  margin-bottom: 15px;
  padding-left: 25px;
}

.knowledge-base-content li {
  margin-bottom: 5px;
}

.knowledge-base-content table {
  width: 100%;
  margin: 20px 0;
  border-collapse: collapse;
}

.knowledge-base-content table th,
.knowledge-base-content table td {
  border: 1px solid #dee2e6;
  padding: 12px;
  text-align: left;
}

.knowledge-base-content table th {
  background-color: #373643;
  color: white;
  font-weight: 600;
}

.knowledge-base-content table tr:nth-child(even) {
  background-color: #f8f9fa;
}

.knowledge-base-content .alert {
  padding: 15px;
  margin: 20px 0;
  border: 1px solid transparent;
  border-radius: 5px;
}

.knowledge-base-content .alert-info {
  color: #0c5460;
  background-color: #d1ecf1;
  border-color: #bee5eb;
}

.knowledge-base-content .alert-warning {
  color: #856404;
  background-color: #fff3cd;
  border-color: #ffeaa7;
}

.knowledge-base-content .alert-success {
  color: #155724;
  background-color: #d4edda;
  border-color: #c3e6cb;
}

.knowledge-base-content img {
  max-width: 100%;
  height: auto;
  margin: 15px 0;
  border-radius: 5px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

#tableOfContents {
  max-height: 70vh;
  overflow-y: auto;
}

#tableOfContents a {
  color: #495057;
  text-decoration: none;
  display: block;
  padding: 5px 0;
  border-bottom: 1px solid #f8f9fa;
  transition: all 0.2s;
}

#tableOfContents a:hover {
  color: #18cb96;
  padding-left: 10px;
}

#tableOfContents .toc-h1 {
  font-weight: bold;
  margin-top: 10px;
}

#tableOfContents .toc-h2 {
  padding-left: 15px;
  font-size: 0.9em;
}

#tableOfContents .toc-h3 {
  padding-left: 30px;
  font-size: 0.85em;
  color: #6c757d;
}

/* Print styles */
@media print {
  .card-header,
  .breadcrumb,
  #tocSidebar,
  .btn {
    display: none !important;
  }
  
  .card {
    border: none !important;
    box-shadow: none !important;
  }
  
  .col-md-9 {
    flex: 0 0 100% !important;
    max-width: 100% !important;
  }
  
  .knowledge-base-content {
    font-size: 12px !important;
  }
  
  .knowledge-base-content h1 {
    page-break-before: always;
  }
  
  .knowledge-base-content h1:first-child {
    page-break-before: auto;
  }
}

/* Mobile responsiveness */
@media (max-width: 768px) {
  #tocSidebar {
    display: none !important;
  }
  
  #tocSidebar.show {
    display: block !important;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.5);
    z-index: 1050;
  }
  
  #tocSidebar.show .card {
    position: absolute;
    top: 50px;
    left: 20px;
    right: 20px;
    max-height: calc(100vh - 100px);
    overflow-y: auto;
  }
  
  .col-md-9 {
    flex: 0 0 100% !important;
    max-width: 100% !important;
  }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Generate Table of Contents
    generateTableOfContents();
    
    // Toggle sidebar on mobile
    document.getElementById('toggleSidebar').addEventListener('click', function() {
        const sidebar = document.getElementById('tocSidebar');
        sidebar.classList.toggle('show');
    });
    
    // Close sidebar when clicking outside on mobile
    document.getElementById('tocSidebar').addEventListener('click', function(e) {
        if (e.target === this) {
            this.classList.remove('show');
        }
    });
});

function generateTableOfContents() {
    const headers = document.querySelectorAll('.knowledge-base-content h1, .knowledge-base-content h2, .knowledge-base-content h3');
    const toc = document.getElementById('tableOfContents');
    
    if (headers.length === 0) return;
    
    let tocHTML = '';
    
    headers.forEach((header, index) => {
        // Create unique ID for header
        const id = 'heading-' + index;
        header.id = id;
        
        // Remove emoji from text for cleaner TOC
        const text = header.textContent.replace(/[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu, '').trim();
        
        // Determine heading level
        const level = header.tagName.toLowerCase();
        
        tocHTML += `<a href="#${id}" class="toc-${level}">${text}</a>`;
    });
    
    toc.innerHTML = tocHTML;
    
    // Smooth scrolling for TOC links
    toc.querySelectorAll('a').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
                
                // Close mobile sidebar
                document.getElementById('tocSidebar').classList.remove('show');
            }
        });
    });
}

// Search functionality (basic)
function searchKnowledgeBase(query) {
    const content = document.querySelector('.knowledge-base-content');
    const sections = content.querySelectorAll('h1, h2, h3, p, li');
    
    if (!query) {
        // Show all content
        sections.forEach(section => {
            section.style.display = '';
        });
        return;
    }
    
    const regex = new RegExp(query, 'gi');
    
    sections.forEach(section => {
        if (section.textContent.match(regex)) {
            section.style.display = '';
            // Highlight matching text
            section.innerHTML = section.innerHTML.replace(regex, '<mark>$&</mark>');
        } else {
            section.style.display = 'none';
        }
    });
}

// Add search functionality if needed
function addSearchBox() {
    const cardTools = document.querySelector('.card-tools');
    const searchHTML = `
        <div class="input-group me-2" style="width: 250px;">
            <input type="text" class="form-control form-control-sm" 
                   placeholder="Search knowledge base..." 
                   id="knowledgeSearch">
            <button class="btn btn-outline-secondary btn-sm" type="button" onclick="clearSearch()">
                <i class="bi bi-x"></i>
            </button>
        </div>
    `;
    
    cardTools.insertAdjacentHTML('afterbegin', searchHTML);
    
    // Add search functionality
    document.getElementById('knowledgeSearch').addEventListener('input', function() {
        searchKnowledgeBase(this.value);
    });
}

function clearSearch() {
    document.getElementById('knowledgeSearch').value = '';
    searchKnowledgeBase('');
}

// Back to top functionality
window.addEventListener('scroll', function() {
    const backToTop = document.getElementById('backToTop');
    if (!backToTop) {
        // Create back to top button
        const button = document.createElement('button');
        button.id = 'backToTop';
        button.className = 'btn btn-primary position-fixed';
        button.style.cssText = 'bottom: 20px; right: 20px; z-index: 1000; display: none;';
        button.innerHTML = '<i class="bi bi-arrow-up"></i>';
        button.onclick = () => window.scrollTo({ top: 0, behavior: 'smooth' });
        document.body.appendChild(button);
    }
    
    const backToTopBtn = document.getElementById('backToTop');
    if (window.pageYOffset > 300) {
        backToTopBtn.style.display = 'block';
    } else {
        backToTopBtn.style.display = 'none';
    }
});
</script>
@endsection